services:
  # Base de datos para alumnos
  db_alumnos:
    image: mysql:8.0
    container_name: db_alumnos
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: alumnos
      MYSQL_USER: moises
      MYSQL_PASSWORD: itm123
    volumes:
      - db_alumnos_data:/var/lib/mysql
      - ./basededatos/alumnos.sql:/docker-entrypoint-initdb.d/alumnos.sql
    ports:
      - "3306:3306"


  # Base de datos para maestros
  db_maestros:
    image: mysql:8.0
    container_name: db_maestros
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: maestros
      MYSQL_USER: moises
      MYSQL_PASSWORD: itm123
    volumes:
      - db_maestros_data:/var/lib/mysql
      - ./basededatos/maestros.sql:/docker-entrypoint-initdb.d/maestros.sql
    ports:
      - "3307:3306"


  # Aplicación para maestros
  maestros:
    build:
      context: .
      dockerfile: dockerfile_maestros
    container_name: maestros
    environment:
      DB_HOST: db_maestros
      DB_NAME: maestros
      DB_USER: moises
      DB_PASSWORD: itm123
      API_ALUMNO: alumnos
    depends_on:
      - db_maestros
    ports:
      - "8081:80"

     # Aplicación para alumnos
  alumnos:
    build:
      context: .
      dockerfile: dockerfile_alumnos
    container_name: alumnos
    environment:
      DB_HOST: db_alumnos
      DB_NAME: alumnos
      DB_USER: moises
      DB_PASSWORD: itm123
    depends_on:
      - db_alumnos
    ports:
      - "8082:80"


  # PhpMyAdmin para2 la base de datos de alumnos
  phpmyadmin_alumnos:
    image: phpmyadmin:latest
    container_name: phpmyadmin_alumnos
    environment:
      PMA_HOST: db_alumnos
      PMA_USER: moises
      PMA_PASSWORD: itm123
    depends_on:
      - db_alumnos
    ports:
      - "8090:80"


  # PhpMyAdmin para la base de datos de maestros
  phpmyadmin_maestros:
    image: phpmyadmin:latest
    container_name: phpmyadmin_maestros
    environment:
      PMA_HOST: db_maestros
      PMA_USER: moises
      PMA_PASSWORD: itm123
    depends_on:
      - db_maestros
    ports:
      - "8091:80"


volumes:
  db_alumnos_data:
  db_maestros_data:

